export const APP_LOADING = 'app_loading'
export const APP_READY = 'app_ready'

export const BUBBLES_LOADED = 'bubbles_loaded'

export const UPDATE_SIZE = 'update_size'
export const UPDATE_SIZE_WIDTH = 'update_size_width'
export const UPDATE_SIZE_HEIGHT = 'update_size_height'
export const UPDATE_BACKGROUND = 'update_background'
export const GENERATE_SPRITES = 'generate_sprites'
export const UPDATE_SPRITE = 'update_sprite'
export const DELETE_SPRITE = 'delete_sprite'
export const SELECT_SPRITE = 'select_sprite'
export const DESELECT_SPRITE = 'deselect_sprite'
export const DRAG_START_PROXY = 'drag_start_proxy'
export const DRAG_END_PROXY = 'drag_end_proxy'
